name: kiilib_core
description: Kii core Library
author: fkm <fkm@mokelab.com>
homepage: https://github.com/mokelab/KiiLib_Dart_Core

version: 0.0.1+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

dev_dependencies:
